# Generated by Django 3.1.3 on 2020-11-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0003_auto_20201123_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completion',
            new_name='completed',
        ),
    ]
